version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: travel-planner-postgres
    restart: always
    environment:
      POSTGRES_DB: travel_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: travel-planner-redis
    ports:
      - "6379:6379"